### PR TITLE
Added callbacks to the a play method

### PR DESCRIPTION
**Pull request by jsimnz**
This allows more 'instance' based callbacks to be run once for a specific play method call, as opposed to the global callback added in the object constructor. Additionally added tests and updated readme to reflect the new feature.

### CODE REVIEW

**Comment by maxwellito** [comment]
Hallo!
You mark a good point about the callback.
You're not the first one to mention it and it makes completely sense in terms of what developers needs. However, I was thinking to adapt the works of the #85 to the core library then add the callback functionality. Which would might make the current callback deprecated. But this would be part of a big rewriting of the API. Do you want to be involved? :)

But your PR looks good. Let me think about if the new API I plan to implement would affect your work, but this should work :)

**Comment by jsimnz** [comment]
Well they way I see it right now is that there could be 3 different types of callbacks.

- The global callback for the vivus object
- The callback to which I implemented, for an individual play call
- The callback described in #85 which is a per path callback (Not sure if that should be defined globablly on the constructor, or on a individual play method call.

All three of which I see having they're place, however figuring out the API for the instance callbacks certainly needs to be figured so they easy and simple to both use if necessary.

I'm happy to contribute bits and pieces. To be honest though, we only use vivus for one section of our website, however I like in general contributing to OS projects I use so I am indeed interesting in helping out.

**Comment by yellow1912** [comment]
Is there any plan to make it possible?

**Comment by maxwellito** [comment]
The idea is very interesting, however I would like to find a way to integrate it without disrupting the API. I start to have a lot of different points/features to integrate, but it will be for the `v1.x`. Otherwise all of these will be breaking changes...  I need to put my head back into the project :-/

**Comment by maxwellito** [comment]
Ok, after @yellow1912 message, I gave a second look to this PR. Your implementation of the callback works like a charm and respect the current API, which is super cool. Plus you wrote tests 👍 
However I have a silly case 

```js
// Play the animation with a callback
myVivus.play(myCallback);

// Then later but before the end of the animation
myVivus.play(-1);
```

This will execute `myCallback` (at the end of `-1` play) even if the first animation didn't hit the end. I'm not sure this the expected behavior. If so, you should set `this.instance_callback = null;` straight at the start of the `play` method.

Btw, can you remove the `dist/` files from the PR to avoid merge conflicts? I will compile on my machine and push to NPM.

*Sorry for the delay and thanks for your PR :)*

**Comment by jsimnz** [comment]
Yeah, didn't 100% think through some of the edge cases on concurrent calls to `play()`.

Nice cleanup/fixes on the PR too. Glad this was merged in. Hopefully this will add sufficient value to people.

Cheers,

**Pull request merged**
