### PR TITLE
add doclets.io config

### PR DESCRIPTION
**Pull request by lipp**
Adds documentation to [doclets.io](https://doclets.io) service. Future tags and master branch will be published automatically.

[Preview generated with my account](https://doclets.io/lipp/vivus/add-to-doclets)

@maxwellito  If you like this, you are very welcomed to login to https://doclets.io with GitHub OAuth. If you don't like it, I'd be happy to hear what you don't like about it :)

Steps required (3min):
1) @maxwellito   logs in to doclets.io
2) @maxwellito   adds vivus
3) someone merges this PR

### CODE REVIEW

**Comment by maxwellito** [comment]
Hallo,
Sorry about the delay. 
I didn't know docklets.io which looks pretty nice and usefull.
I had a look to the generated documentation you made and I'm a bit skeptical. The documentation cover all the methods, however a lot of them are restricted to the core and have no reasons to be in a public documentation. Or I'm missing something :)

**Comment by lipp** [comment]
@maxwellito sorry for my delay too :) 
You can "hide " items by adding @private or @ignore tags to the respective comment block.

**Comment by maxwellito** [comment]
In that case, it might be useful. I like this because it respect a standard. But the jsDoc of Vivus needs to be updated. Do you want me to help you to do it, or shall I make it?

**Comment by lipp** [comment]
@maxwellito If you point me the direction, I'm glad to help...

**Comment by maxwellito** [comment]
Thanks :)
Technically, only the `Controls` section and animation functions in Vivus should be in the documentation. About the `README` and `HACKS` should also be included (as you did :). But a general review of the jsdoc would be cool too. Some comments must be awful and attributes are missing.

**Pull request closed without merging**
