### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Add CDNJS link, vivus is no available on CDNJS :smile:

### CODE REVIEW

**Comment by maxwellito** [comment]
Hello,
Sorry for the delay.
I just had a look to your PR. I'm a bit skeptical about this CDN. 

- I currently cannot access the website (which is a bit dangerous for dev using your CDN for production). I hope it's on my end.
- Not sure your link is the link to the script itself, but the vivus page on CDNJS

Does your CDN get the latest version automatically?

Thanks,
Max

**Comment by PeterDaveHello** [comment]
Hi @maxwellito 

Thanks for your reply, the page looks by my side, if you still have the problem, I would like to know more details if you don't mind, the link is to the vivus page on CDNJS, not the script itself, we automatically update the libraries, but we do not support the `latest` syntax in the url because it has potential issues with cache, so that I just link to the page.

Best,
Peter

**Comment by maxwellito** [comment]
Ok, sorry last it was down. I couldn't access the page (and homepage).
Well, it works for me, as long as I don't need to update it :)

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
