### PR TITLE
Added useAsSVG option

### PR DESCRIPTION
**Pull request by Nerdissimo**
Added useAsSVG option.
It will include .svg file as svg html tag instead of object html tag.
Use it to make your svg clickable.

### CODE REVIEW

**Comment by maxwellito** [comment]
Hi there,
I'm really sorry for the late reply. I've been AFK for few days.
First, thank you for your PR, I really appreciate.

Unfortunately, I have to ask you some help, because I don't really get what your code is supposed to do. Could you provide me an example please? Thanks :)

**Comment by Nerdissimo** [comment]
Hi!
First of all, I really like vivus!
I'm trying to use it for some wow-effect :D

I tried to explain what I want to do at this URL http://www.nerdissimo.it/vivus-example/.
You could find there an explanation of what I supposed to do and an example code.
I hope I didn't do a mess :p
In case, please explain me where I was wrong and close the pull request.
If you have some other way to do that, please tell and I will try to fix my code.

Thank you very much in advance!

**Comment by maxwellito** [comment]
Sorry for the delay, I'm really busy recently and I also was on holidays. Away from keyboards.

Which is a shame when I have such nice contributors having amazing ideas.

Thanks a lot for the demo. And everything make sense now. But in the end I'm even wondering why putting this as an option? Because I don't think you break any of the current code (I'll do some tests) and this is the behavior people wants. This should be the default behavior, don't you think?

I'll give a closer look to this. This is amazing.
Thanks a lot :)

**Comment by Nerdissimo** [comment]
Don't worry, I can understand you :)
I'm busy too, recently...

I'm glad you like my current pull request :)
If you think this shouldn't be an option, I could send you another pull request with this code that works as default behavior. Let me know how I can be useful.

Thank you very much for the time you invest in vivus and in my pull request :)

**Comment by maxwellito** [comment]
Hey @Nerdissimo 
I'm still playing to add this feature but it break with some old cases. It's a bit silly because it's rare cases that aren't mentioned in the doc: use Vivus constructor with an `object` element. So I might refactor and remove some of these.

But your trick is so amazing. I didn't know it was possible, I thought it was impossible to move content between the main document and shadow DOM. But what I really love it's to can use the CSS to apply style on SVGs, it was like xmas to me

jonah-hill-mars-volta

So, I'm working on the `dev` branch. When I have something I'll post it here :)
Thanks again!

**Comment by davmillar** [comment]
If I recall correctly, object is favored over inline SVG mostly to support older browsers. Because of that, maybe instead of `useAsSVG` as an option and defaulting to object, call the option `legacySupport` and have it default to inline SVG?

**Comment by maxwellito** [comment]
Hi David,
Can you tell more about this preference for `object` on old browsers? I always stopped at IE9 because [caniuse.com](http://caniuse.com/#feat=svg) mention 8 and under as incompatible with SVG 1.1. I also rejected an issue yesterday because it was concerning IE8 :-$ I try to not go deep into compatibility for old browsers. Especially now Microsoft stopped supporting them. *It's funny, every time I talk about old browsers, I only think about Internet Explorer. Maybe you had other ones in mind?*

Maybe I should try properly my new code on old browser. It would fallback automatically by displaying the SVG without animation it because it cannot access the SVG methods to get path lengths. That's the best it can happen, I think.

Sorry, I realised over the commits that the list of options keeps growing. So if I can avoid adding one for supporting old browser force to use new technologies, I try to.

I hope I don't look like a grumpy cat who say no to every requests ;)

**Comment by davmillar** [comment]
No worries, and I might be thinking of something else, but I seem to recall
some old version of a browser supporting SVG as an object but not inclined
SVG. Maybe Firefox 2? Oh well. I agree — probably best to get with the
future instead of worrying about legacy support.

**Comment by Nerdissimo** [comment]
Hi @maxwellito!
I'm really sorry! Sorry if I reply you just now, but I was really busy after my holiday (afw) :(

I saw you found a work around for an issue (I was scouting on the same problem before my holiday) so, thanks again for your time :p
You also committed something on dev branch (and my name is now in the *special thanks* :D) so I suppose you did it! Was it an hard task? There's anything else I can do about it? Do you think it will be merged with the branch "master"? LMK

Again, I'm sorry about my delayed reply and I really thank you to spend your time on this cool project :)

Bye!
Sergio

**Comment by maxwellito** [comment]
Hallo!
To make it short, it should be merged to `master` soon. I'm finishing a manual test page for visual glitches and behavior. Should be pushed soon. It was not that complex, but I had to keep a retro compatibility. Maybe by tonight I'll post it on `dev` and ask for quick feedback before I merge and push to NPM.

Thanks again :)

Max

**Comment by maxwellito** [comment]
But here is the [v0.3.0](https://github.com/maxwellito/vivus/tree/dev) ready to be released. It's on the dev branch. I added a manual test page to check the retro-compatibility in the future. I don't know if somebody would like to test it quickly, but feedback is always welcome. Otherwise it should be published in the next days. :)

**Comment by maxwellito** [comment]
Ok, I'm sad to not merge your code, but your contribution made (to me) an important improvement in the library. You already mention your name in the `Thanks` section. I thinks it's important to mention the devs who made an important contribution. I feel like a twat to not have done that earlier. 

v0.3.0 is alive. I hope I don't break anything :-S

Thanks again for your PR. Don't hesitate to come with new improvements!

**Comment by Nerdissimo** [comment]
Hey!
Don't worry about the merge! Vivus was improved anyway, so it's ok :p
I'm sorry I wasn't able to test vivus before the 0.3.0 release, but I was busy (as usual…). I hope I will test it as soon as possible.

Thank you very much!
I hope we could work together on vivus or any other project in the future :)

Bye!
Sergio

**Comment by Nerdissimo** [comment]
Hey!
Don't worry about the merge! Vivus was improved anyway, so it's ok :p
I'm sorry I wasn't able to test vivus before the 0.3.0 release, but I was
busy (as usual…). I hope I will test it as soon as possible.

Thank you very much!
I hope we could work together on vivus or any other project in the future :)

Bye!
Sergio

Sergio


2016-01-21 1:58 GMT+01:00 maxwellito <notifications@github.com>:

**Pull request closed without merging**
