### PR TITLE
Add support for non-scaling-stroke vector effect. 

### PR DESCRIPTION
**Pull request by alexgurr**
Hey!

I've added new scaling support for path lengths and included a test with two different kinds of path (identical other than this attribute).

Fixes https://github.com/maxwellito/vivus/issues/112

Would love someone to test a bunch of SVGs manually to prove this, but I've tested with my own line graph and it works.

### CODE REVIEW

**Comment by maxwellito** [comment]
Thanks @alexgurr for your PR! The code seems great, I need to test it as well with few examples tho. Otherwise excellent PR, you've updated the tests as well. I try to get back to you once I have few examples. (my bank holiday weekend is a bit chaotic but I'll try to be fast)

**Comment by alexgurr** [comment]
Thanks for the kind words. No rush, I'm currently using a GitHub path in my package json file! Test it thoroughly !

**Comment by maxwellito** [comment]
Ok, after few tests I remember why I didn't implemented this back in the days. It's very tough (if not impossible) to provide an correct value of the path length after transformation. Because the calculation will be based on the scale (width and height) of the element.

For example: `(the diagonal of a square) * 2 !== (diagonal of a square) with scale(2, 1)`

I did a little test case :  http://maxwellito.github.io/drafts/vivus-issue-234/

The robust solution would be to calculate every path length manually and not via `.getTotalLength()`. But that's not something I'm ready to jump into!
I'm still digging into maths to check if I'm not missing something that could solve the case. I keep you posted :)

**Comment by alexgurr** [comment]
I've noticed this library uses pythagoras' theorem to calculate individual point lengths. Not sure if there's some logic we can grab from here? https://github.com/ConnorAtherton/walkway/blob/master/src/walkway.js

**Comment by alexgurr** [comment]
I would also suggest that a solution that partially works (seems to fix 80% of your examples) is potentially better than nothing?

**Comment by maxwellito** [comment]
Definitely, I would make it clear in the docs that the feature is not 100% reliable but should fit most cases.

I was investigating to use width and height (cf [draft](https://github.com/maxwellito/drafts/blob/gh-pages/vivus-issue-234/vivus.pr.edit.js#L1195-L1197)) but still not perfect. I was also looking is the Pythagorean theorem, but still looking :)

Also, this make me think that, when Vivus is parsing a SVG with `non-scaling-stroke`, it must be remapped when the SVG is resized (due to window resize of other event).

**Comment by alexgurr** [comment]
```Also, this make me think that, when Vivus is parsing a SVG with non-scaling-stroke, it must be remapped when the SVG is resized (due to window resize of other event).``` - I noticed this. In the app I'm using this library, I just kill the animation and reset the stroke array with `!important` in the parent. Wasn't sure if we wanted to handle this in the library. I would suggest if we do, we might need to attach an optional observer to the SVG for when it changes size and recalculate the stroke as you mentioned.

I can try and help with some further stuff here if you can provide me that debug HTML and how to run it? My biggest issue was I couldn't run any of the manual examples.

**Comment by maxwellito** [comment]
Hey @alexgurr 

So, after a lot of tests cases I reached this conclusion: while scaling for a line length, it's fine to go bigger than smaller. It might make the line appearing super fast in the worst case scenario, but won't start/stop right in the middle (and look terribly clunky). To do so, I take the biggest scale between X-axis and Y-axis, because it will cover the extreme cases. 

I updated my draft : [diff](https://github.com/maxwellito/drafts/commit/c2a6433d03e35f591e05d3a4d213ce5c857993cf) and [demo]( http://maxwellito.github.io/drafts/vivus-issue-234/)

About the re-mapping, I'm happy to ask users to make a call to `this.mapping() + this.drawer()` (but I need some proper testing on this tho)

Tell me what you think :)

**Comment by alexgurr** [comment]
Yeah looks good to me. I think that's a reasonable compromise for a consistently working solution.

I think we can just add a section in the documentation explaining the use of mapping, draw and reset and an observer, maybe with a code example?

(Just a side note, drawer is a mis-spell and should simply be draw).

**Comment by maxwellito** [comment]
Hehe, I know how bad this codebase is about spelling mistakes. My english has slightly improved since. But I never thought this little library would get so much attention. I'll make some changes, feel free to add more :)

About the inline style, I'd like to leave it to `.mapping`. Using inline style is already a trick to get the highest priority, I don't want to make it more complex with `!important` tags.

I have only one concern, its about leaving the responsibility to the user to set up an observer when the SVG has `non-scaling-vector` props. The most common issue I had to face with this project was users not understanding the difference between a stroke based SVG, and a filled one. This is why I doubt a lot about users understanding the implications of the non-scaling. I have 2 approaches:

- Vivus set up a Resize Observer on the SVG and update the path when needed
- Ask users to set up the observer themselves. But show a warning when a `non-scaling-vector` is detected.

About your PR, let's keep it, if you don't mind I would like to make PRs to your branch (or code suggestions) so we can keep the conversation here. I'll add examples in the manual tests as well.

**Comment by alexgurr** [comment]
The important style stuff is hacks in my app to get round the animation reset. I'd **never** expect to implement it in the library.

I see what you're saying. I guess it's as simple as do we take the time to build the observer logic or do we offload that to the user?

My only concern with the observer approach is that it's natively throttled. This means (in theory), as the window is resized there will be slight delays in the calculation and change of stroke offset. This will mean there's always weird gaps (briefly) as the resizing occurs. Observation resizers are also **one way** of doing this. Potentially we could make some recommendations/examples but let the user decide?

**Comment by maxwellito** [comment]
Ok, I have most of it : code change, readme update, new manual test. However, I still have an issue with the Observer. I will have a closer look later

**Comment by alexgurr** [comment]
Ok this is good to go now.

**Review by maxwellito — APPROVED** [review]
Ready to go!

@alexgurr thank you very much for your patience and going thru it with me. I wish everybody in the OSS world would take time, as you did, to implement features that matter to them. Big kudos to you

**Comment by alexgurr** [comment]
Thanks for your time too :). It'll make an appearance in my package react-simple-line-chart when I get round to finishing it!

**Pull request merged**
