### PR TITLE
Patch build for universal environments

### PR DESCRIPTION
**Pull request by maxwellito**
Patch related to https://github.com/maxwellito/vivus/issues/152 from @rauchg

### CODE REVIEW

**Comment by rauchg** [comment]
LGTM!

**Comment by rauchg** [comment]
Although:

```
/**
 * Alias for document element
 *
 * @type {DOMelement}
 */
Vivus.prototype.docElem = window.document.documentElement;
```

This will also fail on the server

**Comment by rauchg** [comment]
Same with:

```
requestAnimFrame = (function () {
  return (
    window.requestAnimationFrame       ||
    window.webkitRequestAnimationFrame ||
    window.mozRequestAnimationFrame    ||
    window.oRequestAnimationFrame      ||
    window.msRequestAnimationFrame     ||
    function(/* function */ callback){
      return window.setTimeout(callback, 1000 / 60);
    }
  );
})();
```

**Comment by maxwellito** [comment]
Should I execute these assignations in the constructor? Or the problem will remain the same?

**Comment by maxwellito** [comment]
Sorry about the delay. I think I figured out the problem you mentioned. All use of `window` is now waiting initialization. None during the original execution.

**Comment by rauchg** [comment]
LGTM

**Comment by maxwellito** [comment]
Thanks @rauchg

**Pull request merged**
